config/routes.rb
Rails.application.routes.draw do
  resources :repos

  root 'repos#index'

end

app/models/repo.rb
# this class is pure crap. TODO refactor
class Repo < ActiveRecord::Base
    validates :name, presence: true
    
    def self.update_from_server! (user, pass)
        remote_data = get_remote_data(user, pass)
        get_repos_from_remote_data(user,pass,remote_data)
    end
 private 
 
    def self.make_get_request_to_stash_api(user, pass, request_route)
        params = YAML::load(File.open(Rails.root.to_s + "/config/config.yml"))
        uri = URI.parse(params["stash_url"] + request_route)
        http = Net::HTTP.new(uri.host, uri.port)
        req = Net::HTTP::Get.new(uri.request_uri)
        req.basic_auth(user, pass)
        http.use_ssl = (uri.scheme == "https")
        http.request(req)
    end
    
    def self.get_remote_data(user, pass)
        make_get_request_to_stash_api(user, pass, "/rest/api/1.0/repos?limit=500").body
    end
    MEGABYTE = 1024 * 1024
    
    def self.get_repos_from_remote_data (user, pass, data)
        slugs = JSON.parse(data)["values"].map {|v| {:name => v["slug"], :project_name => v["project"]["name"], :project_key => v["project"]["key"]} }
        slugs.each do
            |s|
            # update size
            size = JSON.parse(make_get_request_to_stash_api(user, pass, "/rest/reposize/latest/projects/" + s[:project_key] + "/repos/" + s[:name]).body)["sizeRaw"].to_f/(MEGABYTE)
            has_readme = JSON.parse(make_get_request_to_stash_api(user, pass, "/rest/api/1.0/projects/" + s[:project_key] + "/repos/"+s[:name]+"/browse/README.md?type=true").body).has_key?("type")
            repo = Repo.find_or_initialize_by({:name => s[:name]})
            repo.update({:size => size.round(2), :has_readme_file => has_readme })
            repo.save
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :set_repo, only: [:show]

  # GET /repos
  # GET /repos.json
  def index
    @repos = Repo.all
  end

  # GET /repos/1
  # GET /repos/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repo
      @repo = Repo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repo_params
      params.require(:repo).permit(:name, :size, :has_readme_file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>git Hall of Shame</title>
  <script src="assets/javascripts/sorttable.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- This is where the header goes -->
<div class='header'>
  <a> All repos </a>
  <a> Top 10    </a>
</div>

<%= yield %>

</body>
</html>

app/views/repos/index.html.erb
<p id="notice"><%= notice %></p>

<strong><%= "Showing all " + @repos.size.to_s + " repos" %></strong>

<table class="sortable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th>Has readme  file</th>
      <th>Has LICENSE file</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @repos.each do |repo| %>
      <tr>
        <td><%= link_to repo.name, repo %></td>
        <td><%= repo.size %></td>
        <td><%= repo.has_readme_file %></td>
        <td>  <!-- TODO  --></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/repos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @repo.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @repo.size %>
</p>

<p>
  <% if @repo.has_readme_file %>
    <strong class='good'>Has readme file</strong>
  <% end %> 
</p>

<%= link_to 'Back', repos_path %>